# Generated by Django 3.2.12 on 2022-03-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='this is My amazing BLOG!!', max_length=50),
        ),
    ]
